### PR TITLE
Committed Test1_15  and Test_15_By_Tester1 in Ohida tester branch1

### PR DESCRIPTION
**Pull request by ohidaTester1**
Hi QA lead azizaohida , I  have uploaded  my first branch_1 have edited Test1_15  and created Test_15_By_Tester1 class.
You will find the automation testing regarding sign in functionality. Please revies the codes.  Thanks.

### CODE REVIEW

**Comment by azizaohida** [comment]
Hi Tester1 , your code looks  good. Please check the condition steps again for making easier.

**Comment by azizaohida** [comment]
Hi Tester1 , Your code looks good. But checks the condition steps again for making it easier.

**Comment by ohidaTester1** [comment]
hi lead I have updated  code in my conditions.

**Comment by azizaohida** [comment]
Hi Tester1, Your code is perfect .  You can merge it now.  Thanks regards

QA lead.

**Pull request merged**
